### ISSUE TITLE
Log Bug Fix

### ISSUE THREAD

**Issue by YLee2121** [C-KLex/GitEducation#13]
# Bug

## Remove `-> None()` 

My mistake, this would affect the function calling. 

## File Path 

Change the file path from `log.csv` to `Calendar_CLI/Log.csv`

## Row Writing

The function doesn't write a new row properly.

![image](https://github.com/C-KLex/GitEducation/assets/87312700/3d8e3752-56b3-4681-9a0c-dee36ed81c11)

Change to this.

![image](https://github.com/C-KLex/GitEducation/assets/87312700/dc7d9227-5e66-4429-a298-ea6371c8f18c)

## Last Word

Create a new branch, fix the bug, make sure it can act properly, then open a PR.

**Comment by Dazeofcitywalk** [comment]
Thanks for your review!
I have solved the "remove" and "file path" bug.
As for the row writing template, I wonder if it can write a new line in inverse chronological order. (If I understand it correctly, it means that newest date on the top and oldest date at the bottom...?

**Comment by YLee2121** [comment]
> Thanks for your review! I have solved the "remove" and "file path" bug. As for the row writing template, I wonder if it can write a new line in inverse chronological order. (If I understand it correctly, it means that newest date on the top and oldest date at the bottom...?

Yes, you are right, then my code is not suitable for this case. Please go ahead and do what you think is the best.

**Comment by Dazeofcitywalk** [comment]
Fixed the row writing bug, I think it can add a new line on the top of the data frame now.
(also modified file path, I wrongly typed "Calender"

**Comment by YLee2121** [comment]
> Fixed the row writing bug, I think it can add a new line on the top of the data frame now. (also modified file path, I wrongly typed "Calender"

Could you open a new PR to submit the change?
